/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConstructorListDto } from '../../models/constructor-list-dto';

export interface ApiConstructorsGetAllConstructorsGet$Plain$Params {
}

export function apiConstructorsGetAllConstructorsGet$Plain(http: HttpClient, rootUrl: string, params?: ApiConstructorsGetAllConstructorsGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ConstructorListDto>>> {
  const rb = new RequestBuilder(rootUrl, apiConstructorsGetAllConstructorsGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ConstructorListDto>>;
    })
  );
}

apiConstructorsGetAllConstructorsGet$Plain.PATH = '/api/Constructors/getAllConstructors';
