---
config:
  layout: dagre
---
flowchart TD
  S01["🏠 S01 - Home"] -->|nav link| S02["📰 S02 - News"]
  S01 -->|nav link| S03["⭐ S03 - Reviews"]
  S01 -->|nav link| S04["🏆 S04 - Results / Standings"]
  S01 -->|cikk kártya| S06["📄 S06 - Article detail"]
  S01 -->|login gomb| S07["🔒 S07 - Login/Register"]
  S01 -->|szavazás kártya| D09["♦ D09 - Poll vote dialog"]
  S01 -->|poll gomb| D08["♦ D08 - Poll add dialog"]
  S01 -->|profil ikon| S08["👤 S08 - Profile"]
  S01 -->|serie kártya| S05

  S02 -->|cikk kártya| S06

  S03 -->|cikk kártya| S06

  S04 -->|menu gomb| S09["⚙️ S09 - Championships"]
  S04 -->|menu gomb| S10["⚙️ S10 - Participations"]
  S04 -->|menu gomb| S11["⚙️ S11 - Drivers"]
  S04 -->|menu gomb| S12["⚙️ S12 - Constructors"]
  S04 -->|menu gomb| S13["⚙️ S13 - Contracts"]
  S04 -->|menu gomb| S14["⚙️ S14 - Entry list"]

  S05["🔎 S05 - Serie detail"]
  S05 --->|cikk kártya| S06
  S05 -->|szavazás kártya| D09
  S05 -->|poll gomb| D08

  S06 -->|szerkesztés| S18["✏️ S18 - Article update"]
  S07 -->|success| S01["🏠 S01 - Home"]

  S09["⚙️ S09 - Championships"] -->|+ gomb| D01["♦ D01 - Championship create"]
  S10["⚙️ S10 - Participations"] -->|+ gomb| D11["♦ D11 - Participation add"]
  S11["⚙️ S11 - Drivers"] -->|+ gomb| D02["♦ D02 - Driver create"]
  S11 -->|szerkesztés| D03["♦ D03 - Driver edit"]
  S12["⚙️ S12 - Constructors"] -->|+ gomb| D04["♦ D04 - Constructor create"]
  S12 -->|szerkesztés| D05["♦ D05 - Constructor edit"]
  S13["⚙️ S13 - Contracts"] -->|+ gomb| D06["♦ D06 - Contract create"]
  S13 -->|szerkesztés| D07["♦ D07 - Contract edit"]

  S14["⚙️ S14 - Entry list"] -->|kártya kattintás| S15["📊 S15 - Entry detail"]
  S14["⚙️ S14 - Entry list"] -->|kártya kattintás| D10["♦ D10 - GP Manage"]

  S15["📊 S15 - Entry detail"] -->|kártya kattintás| D10["♦D10 - GP Manage"]
  S15 -->|Létrehoz| S16["🆕 S16 - Entry create"]

  S16 --> |mentés|S15

  S17["📰 S17 - Article create"] -->|mentés| S06

  S18 -->|mentés| S06

  EP01["▶"] --> S01["🏠 S01 - Home"]
  EP06["▶"] --> S06["📄 S06 - Article detail"]
  EP07["▶"] --> S07["🔒 S07 - Login/Register"]
  EP08["▶"] --> S08["👤 S08 - Profile"]
