/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiArticleImageDraftIdPromoteSlugPost$Params {
  draftId: string;
  slug: string;
}

export function apiArticleImageDraftIdPromoteSlugPost(http: HttpClient, rootUrl: string, params: ApiArticleImageDraftIdPromoteSlugPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiArticleImageDraftIdPromoteSlugPost.PATH, 'post');
  if (params) {
    rb.path('draftId', params.draftId, {});
    rb.path('slug', params.slug, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiArticleImageDraftIdPromoteSlugPost.PATH = '/api/article-image/{draftId}/promote/{slug}';
