/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiArticleDraftsDraftIdImagesSlotPost$Params {
  draftId: string;
  slot: string;
      body?: {
'file'?: Blob;
}
}

export function apiArticleDraftsDraftIdImagesSlotPost(http: HttpClient, rootUrl: string, params: ApiArticleDraftsDraftIdImagesSlotPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiArticleDraftsDraftIdImagesSlotPost.PATH, 'post');
  if (params) {
    rb.path('draftId', params.draftId, {});
    rb.path('slot', params.slot, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiArticleDraftsDraftIdImagesSlotPost.PATH = '/api/article-drafts/{draftId}/images/{slot}';
