/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ContractListDto } from '../../models/contract-list-dto';

export interface ApiContractsGetAllGet$Plain$Params {
}

export function apiContractsGetAllGet$Plain(http: HttpClient, rootUrl: string, params?: ApiContractsGetAllGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ContractListDto>>> {
  const rb = new RequestBuilder(rootUrl, apiContractsGetAllGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ContractListDto>>;
    })
  );
}

apiContractsGetAllGet$Plain.PATH = '/api/Contracts/getAll';
