/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiContractsUpdateIdDriverIdTeamIdPost$Params {
  id: string;
  driverId: string;
  teamId: string;
}

export function apiContractsUpdateIdDriverIdTeamIdPost(http: HttpClient, rootUrl: string, params: ApiContractsUpdateIdDriverIdTeamIdPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiContractsUpdateIdDriverIdTeamIdPost.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('driverId', params.driverId, {});
    rb.path('teamId', params.teamId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiContractsUpdateIdDriverIdTeamIdPost.PATH = '/api/Contracts/update/{id}/{driverId}/{teamId}';
