/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DriverListDto } from '../../models/driver-list-dto';

export interface ApiDriversGetAllDriversGet$Plain$Params {
}

export function apiDriversGetAllDriversGet$Plain(http: HttpClient, rootUrl: string, params?: ApiDriversGetAllDriversGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DriverListDto>>> {
  const rb = new RequestBuilder(rootUrl, apiDriversGetAllDriversGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DriverListDto>>;
    })
  );
}

apiDriversGetAllDriversGet$Plain.PATH = '/api/Drivers/getAllDrivers';
