/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DriverDetailDto } from '../../models/driver-detail-dto';

export interface ApiDriversGetIdGet$Plain$Params {
  id: number;
}

export function apiDriversGetIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiDriversGetIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<DriverDetailDto>> {
  const rb = new RequestBuilder(rootUrl, apiDriversGetIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DriverDetailDto>;
    })
  );
}

apiDriversGetIdGet$Plain.PATH = '/api/Drivers/get/{id}';
