/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DriverDetailDto } from '../../models/driver-detail-dto';

export interface ApiDriversGetAllByChampionshipChampionshipIdGet$Json$Params {
  championshipId: string;
}

export function apiDriversGetAllByChampionshipChampionshipIdGet$Json(http: HttpClient, rootUrl: string, params: ApiDriversGetAllByChampionshipChampionshipIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DriverDetailDto>>> {
  const rb = new RequestBuilder(rootUrl, apiDriversGetAllByChampionshipChampionshipIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('championshipId', params.championshipId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DriverDetailDto>>;
    })
  );
}

apiDriversGetAllByChampionshipChampionshipIdGet$Json.PATH = '/api/Drivers/getAllByChampionship/{championshipId}';
