/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CommentDetailDto } from '../../models/comment-detail-dto';

export interface ApiCommentsGetUsersCommentsGet$Plain$Params {
}

export function apiCommentsGetUsersCommentsGet$Plain(http: HttpClient, rootUrl: string, params?: ApiCommentsGetUsersCommentsGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CommentDetailDto>>> {
  const rb = new RequestBuilder(rootUrl, apiCommentsGetUsersCommentsGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CommentDetailDto>>;
    })
  );
}

apiCommentsGetUsersCommentsGet$Plain.PATH = '/api/Comments/getUsersComments';
