/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CommentDetailDto } from '../../models/comment-detail-dto';

export interface ApiCommentsGetCommentRepliesCommentIdGet$Json$Params {
  commentId: string;
}

export function apiCommentsGetCommentRepliesCommentIdGet$Json(http: HttpClient, rootUrl: string, params: ApiCommentsGetCommentRepliesCommentIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CommentDetailDto>>> {
  const rb = new RequestBuilder(rootUrl, apiCommentsGetCommentRepliesCommentIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('commentId', params.commentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CommentDetailDto>>;
    })
  );
}

apiCommentsGetCommentRepliesCommentIdGet$Json.PATH = '/api/Comments/getCommentReplies/{commentId}';
