/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SeriesListDto } from '../../models/series-list-dto';

export interface ApiSeriesGetAllSeriesGet$Json$Params {
}

export function apiSeriesGetAllSeriesGet$Json(http: HttpClient, rootUrl: string, params?: ApiSeriesGetAllSeriesGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SeriesListDto>>> {
  const rb = new RequestBuilder(rootUrl, apiSeriesGetAllSeriesGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SeriesListDto>>;
    })
  );
}

apiSeriesGetAllSeriesGet$Json.PATH = '/api/Series/getAllSeries';
