/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BrandDetailDto } from '../../models/brand-detail-dto';

export interface ApiBrandGetNameGet$Json$Params {
  name: string;
}

export function apiBrandGetNameGet$Json(http: HttpClient, rootUrl: string, params: ApiBrandGetNameGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<BrandDetailDto>> {
  const rb = new RequestBuilder(rootUrl, apiBrandGetNameGet$Json.PATH, 'get');
  if (params) {
    rb.path('name', params.name, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BrandDetailDto>;
    })
  );
}

apiBrandGetNameGet$Json.PATH = '/api/Brand/get/{name}';
