/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BrandListDto } from '../../models/brand-list-dto';

export interface ApiBrandGetAllGet$Json$Params {
}

export function apiBrandGetAllGet$Json(http: HttpClient, rootUrl: string, params?: ApiBrandGetAllGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<BrandListDto>>> {
  const rb = new RequestBuilder(rootUrl, apiBrandGetAllGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<BrandListDto>>;
    })
  );
}

apiBrandGetAllGet$Json.PATH = '/api/Brand/getAll';
