/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ArticleListDto } from '../../models/article-list-dto';

export interface ApiArticleGetRecentNumberGet$Json$Params {
  number: number;
}

export function apiArticleGetRecentNumberGet$Json(http: HttpClient, rootUrl: string, params: ApiArticleGetRecentNumberGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ArticleListDto>>> {
  const rb = new RequestBuilder(rootUrl, apiArticleGetRecentNumberGet$Json.PATH, 'get');
  if (params) {
    rb.path('number', params.number, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ArticleListDto>>;
    })
  );
}

apiArticleGetRecentNumberGet$Json.PATH = '/api/Article/getRecent/{number}';
