/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ArticleListDtoPagedResult } from '../../models/article-list-dto-paged-result';

export interface ApiArticleGetAllArticlesGet$Json$Params {
  page?: number;
  pageSize?: number;
  tag?: string;
}

export function apiArticleGetAllArticlesGet$Json(http: HttpClient, rootUrl: string, params?: ApiArticleGetAllArticlesGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ArticleListDtoPagedResult>> {
  const rb = new RequestBuilder(rootUrl, apiArticleGetAllArticlesGet$Json.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('tag', params.tag, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ArticleListDtoPagedResult>;
    })
  );
}

apiArticleGetAllArticlesGet$Json.PATH = '/api/Article/getAllArticles';
