/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ArticleRecentDto } from '../../models/article-recent-dto';

export interface ApiArticleGetRecentNumberGet$Plain$Params {
  number: number;
}

export function apiArticleGetRecentNumberGet$Plain(http: HttpClient, rootUrl: string, params: ApiArticleGetRecentNumberGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ArticleRecentDto>>> {
  const rb = new RequestBuilder(rootUrl, apiArticleGetRecentNumberGet$Plain.PATH, 'get');
  if (params) {
    rb.path('number', params.number, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ArticleRecentDto>>;
    })
  );
}

apiArticleGetRecentNumberGet$Plain.PATH = '/api/Article/getRecent/{number}';
