/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ArticleDetailDto } from '../../models/article-detail-dto';

export interface ApiArticleGetSlugGet$Plain$Params {
  slug: string;
}

export function apiArticleGetSlugGet$Plain(http: HttpClient, rootUrl: string, params: ApiArticleGetSlugGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ArticleDetailDto>> {
  const rb = new RequestBuilder(rootUrl, apiArticleGetSlugGet$Plain.PATH, 'get');
  if (params) {
    rb.path('slug', params.slug, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ArticleDetailDto>;
    })
  );
}

apiArticleGetSlugGet$Plain.PATH = '/api/Article/get/{slug}';
