/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PollListDto } from '../../models/poll-list-dto';

export interface ApiPollGetAllGet$Plain$Params {
}

export function apiPollGetAllGet$Plain(http: HttpClient, rootUrl: string, params?: ApiPollGetAllGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PollListDto>>> {
  const rb = new RequestBuilder(rootUrl, apiPollGetAllGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PollListDto>>;
    })
  );
}

apiPollGetAllGet$Plain.PATH = '/api/Poll/getAll';
