/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiPollRemoveVotePollIdPost$Params {
  pollId: number;
  pollOptionId: number;
  userId: number;
}

export function apiPollRemoveVotePollIdPost(http: HttpClient, rootUrl: string, params: ApiPollRemoveVotePollIdPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiPollRemoveVotePollIdPost.PATH, 'post');
  if (params) {
    rb.path('pollId', params.pollId, {});
    rb.path('pollOptionId', params.pollOptionId, {});
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiPollRemoveVotePollIdPost.PATH = '/api/Poll/removeVote/{pollId}';
