/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PollListDto } from '../../models/poll-list-dto';

export interface ApiPollGetByCreatorGet$Json$Params {
  tag?: string;
}

export function apiPollGetByCreatorGet$Json(http: HttpClient, rootUrl: string, params?: ApiPollGetByCreatorGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PollListDto>>> {
  const rb = new RequestBuilder(rootUrl, apiPollGetByCreatorGet$Json.PATH, 'get');
  if (params) {
    rb.query('tag', params.tag, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PollListDto>>;
    })
  );
}

apiPollGetByCreatorGet$Json.PATH = '/api/Poll/getByCreator';
