/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PollDto } from '../../models/poll-dto';

export interface ApiPollGetIdGet$Plain$Params {
  id: string;
}

export function apiPollGetIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiPollGetIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<PollDto>> {
  const rb = new RequestBuilder(rootUrl, apiPollGetIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PollDto>;
    })
  );
}

apiPollGetIdGet$Plain.PATH = '/api/Poll/get/{id}';
