/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ArticleRecentDto {
  authorName?: string | null;
  datePublished?: string;
  id?: number;
  lead?: string | null;
  title?: string | null;
}
