/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ArticleCreateDto {
  content?: string | null;
  grandPrixId?: number | null;
  lead?: string | null;
  title?: string | null;
}
