/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ArticleListDto {
  datePublished?: string;
  id?: string;
  isReview?: boolean;
  lead?: string | null;
  primaryImageUrl?: string | null;
  slug?: string | null;
  title?: string | null;
}
