/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SummaryDto } from '../models/summary-dto';
export interface ArticleCreateDto {
  firstSection?: string | null;
  grandPrixId?: string | null;
  lastSection?: string | null;
  lead?: string | null;
  slug?: string | null;
  summary?: SummaryDto;
  title?: string | null;
}
