/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ArticleDetailDto {
  authorId?: number;
  authorName?: string | null;
  content?: string | null;
  datePublished?: string;
  dateUpdated?: string;
  grandPrixId?: number | null;
  grandPrixName?: string | null;
  id?: number;
  lead?: string | null;
  title?: string | null;
}
