/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ArticleDetailDto {
  authorId?: string | null;
  authorName?: string | null;
  datePublished?: string;
  dateUpdated?: string;
  firstSection?: string | null;
  grandPrixId?: string | null;
  grandPrixName?: string | null;
  id?: string;
  isReview?: boolean;
  lastImageUrl?: string | null;
  lastSection?: string | null;
  lead?: string | null;
  middleSections?: Array<string> | null;
  primaryImageUrl?: string | null;
  secondaryImageUrl?: string | null;
  slug?: string | null;
  thirdImageUrl?: string | null;
  title?: string | null;
}
