/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ArticleUpdateDto {
  content?: string | null;
  grandPrixId?: number | null;
  id?: number;
  lead?: string | null;
  title?: string | null;
}
