/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuthResponse {
  email?: string | null;
  expiresAt?: string;
  role?: string | null;
  token?: string | null;
  userId?: string;
  username?: string | null;
}
