/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BrandCreateDto {
  description?: string | null;
  headQuarters?: string | null;
  name?: string | null;
  principal?: string | null;
}
