/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BrandUpdateDto {
  description?: string | null;
  headQuarters?: string | null;
  id?: number;
  name?: string | null;
  principal?: string | null;
}
