/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ChampionshipCreateDto {
  constructorsName?: string | null;
  driversName?: string | null;
  season?: string | null;
  seriesId?: string;
}
