/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CircuitDetailDto {
  fastestLap?: string | null;
  id?: string;
  length?: number;
  location?: string | null;
  name?: string | null;
  type?: string | null;
}
