/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CommentDetailDto {
  content?: string | null;
  dateCreated?: string;
  dateUpdated?: string;
  downVotes?: number;
  id?: number;
  replyToCommentId?: number | null;
  upVotes?: number;
  userId?: number;
  username?: string | null;
}
