/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CommentDetailDto {
  content?: string | null;
  dateCreated?: string;
  dateUpdated?: string;
  downVotes?: number;
  id?: string;
  replyToCommentId?: string | null;
  upVotes?: number;
  userId?: string;
  username?: string | null;
}
