/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ConstructorCreateDto {
  brandId?: string;
  championships?: number;
  foundedYear?: number;
  headQuarters?: string | null;
  name?: string | null;
  nickname?: string | null;
  podiums?: number;
  seasons?: number;
  teamChief?: string | null;
  technicalChief?: string | null;
  wins?: number;
}
