/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ConstructorStandingsResultDto } from '../models/constructor-standings-result-dto';
export interface ConstructorStandingsDto {
  constructorChampId?: string;
  results?: Array<ConstructorStandingsResultDto> | null;
}
