/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DriverNameRecord } from '../models/driver-name-record';
export interface ConstructorDetailDto {
  brandDescription?: string | null;
  brandId?: number;
  brandName?: string | null;
  championships?: number;
  driverNames?: Array<DriverNameRecord> | null;
  foundedYear?: number;
  headQuarters?: string | null;
  id?: number;
  name?: string | null;
  teamChief?: string | null;
  technicalChief?: string | null;
  totalPodiums?: number;
  totalWins?: number;
}
