/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ContractListDto {
  driverId?: string;
  driverName?: string | null;
  id?: string;
  teamId?: string;
  teamName?: string | null;
}
