/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DefaultFiltersDto {
  driversChampId?: string;
  grandPrixId?: string;
  seriesId?: string;
  session?: string | null;
}
