/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DriverListDto {
  age?: number;
  currentTeam?: string | null;
  id?: string;
  name?: string | null;
  nationality?: string | null;
}
