/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DriverStandingsResultDto } from '../models/driver-standings-result-dto';
export interface DriverStandingsDto {
  driverChampId?: string;
  results?: Array<DriverStandingsResultDto> | null;
}
