/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DriverParticipationDto {
  age?: number;
  driverId?: string;
  driverNumber?: number;
  name?: string | null;
  nationality?: string | null;
  teamName?: string | null;
}
