/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DriverDetailDto {
  age?: number;
  birthDate?: string;
  championships?: number;
  constructorIds?: Array<string> | null;
  driverNumber?: number;
  id?: string;
  name?: string | null;
  nationality?: string | null;
  polePositions?: number;
  totalPodiums?: number;
  totalRaces?: number;
  totalWins?: number;
}
