/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DriverUpdateDto {
  birthDate?: string;
  championships?: number;
  driverNumber?: number;
  id?: number;
  name?: string | null;
  nationality?: string | null;
  polePositions?: number;
  seasons?: number;
  totalPodiums?: number;
  totalRaces?: number;
  totalWins?: number;
}
