/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GrandPrixLookupDto {
  circuitName?: string | null;
  endtime?: string;
  hasResults?: boolean;
  id?: string;
  lapsCompleted?: number;
  location?: string | null;
  name?: string | null;
  raceDistance?: number;
  roundNumber?: number;
  startTime?: string;
}
