/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GrandPrixChampionshipContextDto {
  availableSessions?: Array<string> | null;
  consChampId?: string;
  driversChampId?: string;
  pointSystem?: string | null;
}
