/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CircuitDetailDto } from '../models/circuit-detail-dto';
export interface GrandPrixDetailDto {
  circuitDetail?: CircuitDetailDto;
  circuitId?: number;
  endTime?: string;
  id?: number;
  lapsCompleted?: number;
  name?: string | null;
  raceDistance?: number;
  roundNumber?: number;
  seasonYear?: number;
  seriesId?: number;
  seriesName?: string | null;
  startTime?: string;
}
