/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GrandPrixCreateDto {
  circuitId?: string;
  endTime?: string;
  lapsCompleted?: number;
  name?: string | null;
  raceDistance?: number;
  roundNumber?: number;
  seasonYear?: number;
  seriesId?: string;
  startTime?: string;
}
