/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PollListDto {
  description?: string | null;
  expiresAt?: string;
  id?: string;
  tag?: string | null;
  title?: string | null;
}
