/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PollCreateDto {
  description?: string | null;
  expiresAt?: string;
  options?: Array<string> | null;
  title?: string | null;
}
