/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PollOptionDto {
  id?: number;
  isUserChoice?: boolean;
  text?: string | null;
  voteCount?: number;
  votePercentage?: number;
}
