/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PollOptionDto } from './poll-option-dto';
export interface PollDto {
  authorId?: string | null;
  authorName?: string | null;
  createdAt?: string;
  description?: string | null;
  expiresAt?: string;
  hasVoted?: boolean;
  id?: string;
  isActive?: boolean;
  isExpired?: boolean;
  pollOptions?: Array<PollOptionDto> | null;
  title?: string | null;
  totalVotes?: number;
  userVoteOptionId?: string | null;
}
