/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SeasonOverviewDto {
  date?: string;
  grandPrixName?: string | null;
  grandPrixShortName?: string | null;
  laps?: number;
  teamName?: string | null;
  time?: string | null;
  winnerName?: string | null;
}
