/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SeriesUpdateDto {
  description?: string | null;
  firstYear?: number;
  governingBody?: string | null;
  id?: string;
  lastYear?: number;
  name?: string | null;
}
