/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SeriesCreateDto {
  description?: string | null;
  firstYear?: number;
  governingBody?: string | null;
  lastYear?: number;
  name?: string | null;
}
