/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ResultEditDto } from './result-edit-dto';
export interface SessionEditDto {
  grandPrixId?: string;
  results?: Array<ResultEditDto> | null;
  session?: string | null;
}
