/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SummaryDto {
  fourthSection?: string | null;
  secondSection?: string | null;
  thirdSection?: string | null;
}
