/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserProfileResponse {
  avatarUrl?: string | null;
  email: string | null;
  fullName: string | null;
  hasAvatar?: boolean;
  lastActive?: string | null;
  lastLogin?: string | null;
  role: string | null;
  userId?: string;
  username: string | null;
}
