/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface YearLookupDto {
  constructorsChampId?: string;
  driversChampId?: string;
  pointSystem?: string | null;
  season?: string | null;
}
