/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GrandPrixDetailDto } from '../../models/grand-prix-detail-dto';

export interface ApiGrandPrixGetGrandPrixIdGet$Json$Params {
  grandPrixId: string;
}

export function apiGrandPrixGetGrandPrixIdGet$Json(http: HttpClient, rootUrl: string, params: ApiGrandPrixGetGrandPrixIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<GrandPrixDetailDto>> {
  const rb = new RequestBuilder(rootUrl, apiGrandPrixGetGrandPrixIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('grandPrixId', params.grandPrixId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GrandPrixDetailDto>;
    })
  );
}

apiGrandPrixGetGrandPrixIdGet$Json.PATH = '/api/GrandPrix/get/{grandPrixId}';
