/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CircuitListDto } from '../../models/circuit-list-dto';

export interface ApiGrandPrixGetAllCircuitsGet$Json$Params {
}

export function apiGrandPrixGetAllCircuitsGet$Json(http: HttpClient, rootUrl: string, params?: ApiGrandPrixGetAllCircuitsGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<CircuitListDto>> {
  const rb = new RequestBuilder(rootUrl, apiGrandPrixGetAllCircuitsGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CircuitListDto>;
    })
  );
}

apiGrandPrixGetAllCircuitsGet$Json.PATH = '/api/GrandPrix/getAllCircuits';
