/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GrandPrixDetailDto } from '../../models/grand-prix-detail-dto';

export interface ApiGrandPrixGetSeasonGrandsPrixSeriesIdYearGet$Json$Params {
  seriesId: number;
  year: number;
}

export function apiGrandPrixGetSeasonGrandsPrixSeriesIdYearGet$Json(http: HttpClient, rootUrl: string, params: ApiGrandPrixGetSeasonGrandsPrixSeriesIdYearGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<GrandPrixDetailDto>> {
  const rb = new RequestBuilder(rootUrl, apiGrandPrixGetSeasonGrandsPrixSeriesIdYearGet$Json.PATH, 'get');
  if (params) {
    rb.path('seriesId', params.seriesId, {});
    rb.path('year', params.year, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GrandPrixDetailDto>;
    })
  );
}

apiGrandPrixGetSeasonGrandsPrixSeriesIdYearGet$Json.PATH = '/api/GrandPrix/getSeasonGrandsPrix/{seriesId}/{year}';
