// <auto-generated />
using System;
using Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Context.Migrations
{
    [DbContext(typeof(EfContext))]
    [Migration("20260128191302_AddHasAvatarLogictoUser")]
    partial class AddHasAvatarLogictoUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.News.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("DatePublished")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("FirstSection")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_section");

                    b.Property<string>("FourthSection")
                        .HasColumnType("text")
                        .HasColumnName("fourth_section");

                    b.Property<Guid?>("GrandPrixId")
                        .HasColumnType("uuid")
                        .HasColumnName("grand_prix_id");

                    b.Property<bool>("IsSummary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_summary");

                    b.Property<string>("LastSection")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_section");

                    b.Property<string>("Lead")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lead");

                    b.Property<string>("SecondSection")
                        .HasColumnType("text")
                        .HasColumnName("second_section");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("ThirdSection")
                        .HasColumnType("text")
                        .HasColumnName("third_section");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GrandPrixId");

                    b.ToTable("articles");
                });

            modelBuilder.Entity("Entities.Models.News.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("DownVotes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("downvotes");

                    b.Property<Guid?>("ReplyToCommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("reply_id");

                    b.Property<int>("UpVotes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("upvotes");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("ReplyToCommentId");

                    b.HasIndex("UserId");

                    b.ToTable("comments");
                });

            modelBuilder.Entity("Entities.Models.Polls.Poll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("polls");
                });

            modelBuilder.Entity("Entities.Models.Polls.PollOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("PollId")
                        .HasColumnType("uuid")
                        .HasColumnName("poll_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("PollId");

                    b.ToTable("pollOptions");
                });

            modelBuilder.Entity("Entities.Models.Polls.Vote", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("PollOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("poll_option_id");

                    b.HasKey("UserId", "PollOptionId");

                    b.HasIndex("PollOptionId");

                    b.ToTable("votes");
                });

            modelBuilder.Entity("Entities.Models.RaceTracks.Circuit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("FastestLap")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fastest_lap");

                    b.Property<int>("Length")
                        .HasColumnType("integer")
                        .HasColumnName("length");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("circuits");
                });

            modelBuilder.Entity("Entities.Models.RaceTracks.GrandPrix", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CircuitId")
                        .HasColumnType("uuid")
                        .HasColumnName("circuit_id");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<int>("LapsCompleted")
                        .HasColumnType("integer")
                        .HasColumnName("laps_completed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("RaceDistance")
                        .HasColumnType("integer")
                        .HasColumnName("race_distance");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer")
                        .HasColumnName("round_number");

                    b.Property<int>("SeasonYear")
                        .HasColumnType("integer")
                        .HasColumnName("season_year");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("CircuitId");

                    b.HasIndex("SeriesId");

                    b.ToTable("grands_prix");
                });

            modelBuilder.Entity("Entities.Models.Standings.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("HeadQuarters")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("headquarters");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Principal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("principal");

                    b.HasKey("Id");

                    b.ToTable("brands");
                });

            modelBuilder.Entity("Entities.Models.Standings.Constructor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<int>("Championships")
                        .HasColumnType("integer")
                        .HasColumnName("championships");

                    b.Property<int>("FoundedYear")
                        .HasColumnType("integer")
                        .HasColumnName("founded_year");

                    b.Property<string>("HeadQuarters")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("headquarters");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Podiums")
                        .HasColumnType("integer")
                        .HasColumnName("podiums");

                    b.Property<int>("Seasons")
                        .HasColumnType("integer")
                        .HasColumnName("seasons");

                    b.Property<string>("TeamChief")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("team_chief");

                    b.Property<string>("TechnicalChief")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("technical_chief");

                    b.Property<int>("Wins")
                        .HasColumnType("integer")
                        .HasColumnName("wins");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("constructors");
                });

            modelBuilder.Entity("Entities.Models.Standings.ConstructorCompetition", b =>
                {
                    b.Property<Guid>("ConstructorId")
                        .HasColumnType("uuid")
                        .HasColumnName("constructors_id");

                    b.Property<Guid>("ConstChampId")
                        .HasColumnType("uuid")
                        .HasColumnName("constructors_championship_id");

                    b.HasKey("ConstructorId", "ConstChampId");

                    b.HasIndex("ConstChampId");

                    b.ToTable("constructor_competitions");
                });

            modelBuilder.Entity("Entities.Models.Standings.ConstructorsChampionship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("season");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.ToTable("constructor_champions");
                });

            modelBuilder.Entity("Entities.Models.Standings.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ConstructorId")
                        .HasColumnType("uuid")
                        .HasColumnName("constructor_id");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.HasKey("Id");

                    b.HasIndex("ConstructorId");

                    b.HasIndex("DriverId");

                    b.ToTable("contracts");
                });

            modelBuilder.Entity("Entities.Models.Standings.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<int>("Championships")
                        .HasColumnType("integer")
                        .HasColumnName("championships");

                    b.Property<int>("DriverNumber")
                        .HasColumnType("integer")
                        .HasColumnName("driver_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nationality");

                    b.Property<int>("Podiums")
                        .HasColumnType("integer")
                        .HasColumnName("podiums");

                    b.Property<int>("PolePositions")
                        .HasColumnType("integer")
                        .HasColumnName("pole_positions");

                    b.Property<int>("Seasons")
                        .HasColumnType("integer")
                        .HasColumnName("seasons");

                    b.Property<int>("TotalRaces")
                        .HasColumnType("integer")
                        .HasColumnName("total_races");

                    b.Property<int>("Wins")
                        .HasColumnType("integer")
                        .HasColumnName("wins");

                    b.HasKey("Id");

                    b.ToTable("drivers");
                });

            modelBuilder.Entity("Entities.Models.Standings.DriverParticipation", b =>
                {
                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<Guid>("DriverChampId")
                        .HasColumnType("uuid")
                        .HasColumnName("drivers_championship_id");

                    b.HasKey("DriverId", "DriverChampId");

                    b.HasIndex("DriverChampId");

                    b.ToTable("driver_participations");
                });

            modelBuilder.Entity("Entities.Models.Standings.DriversChampionship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("season");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.ToTable("driver_championships");
                });

            modelBuilder.Entity("Entities.Models.Standings.Result", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ConsChampId")
                        .HasColumnType("uuid")
                        .HasColumnName("constructors_championship_id");

                    b.Property<Guid>("ConstructorId")
                        .HasColumnType("uuid")
                        .HasColumnName("constructor_id");

                    b.Property<int>("ConstructorPoints")
                        .HasColumnType("integer")
                        .HasColumnName("constructor_points");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<int>("DriverPoints")
                        .HasColumnType("integer")
                        .HasColumnName("driver_points");

                    b.Property<Guid>("DriversChampId")
                        .HasColumnType("uuid")
                        .HasColumnName("drivers_championship_id");

                    b.Property<int>("FinishPosition")
                        .HasColumnType("integer")
                        .HasColumnName("finish_position");

                    b.Property<Guid>("GrandPrixId")
                        .HasColumnType("uuid")
                        .HasColumnName("grand_prix_id");

                    b.Property<long>("RaceTime")
                        .HasColumnType("bigint")
                        .HasColumnName("race_time");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session");

                    b.Property<int>("StartPosition")
                        .HasColumnType("integer")
                        .HasColumnName("start_position");

                    b.HasKey("Id");

                    b.HasIndex("ConsChampId");

                    b.HasIndex("ConstructorId");

                    b.HasIndex("DriverId");

                    b.HasIndex("DriversChampId");

                    b.HasIndex("GrandPrixId");

                    b.ToTable("results");
                });

            modelBuilder.Entity("Entities.Models.Standings.Series", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("FirstYear")
                        .HasColumnType("integer")
                        .HasColumnName("first_year");

                    b.Property<string>("GoverningBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("governing_body");

                    b.Property<int>("LastYear")
                        .HasColumnType("integer")
                        .HasColumnName("last_year");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("series");
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("HasAvatar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_avatar");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("user")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Entities.Models.News.Article", b =>
                {
                    b.HasOne("Entities.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.Models.RaceTracks.GrandPrix", "GrandPrix")
                        .WithMany()
                        .HasForeignKey("GrandPrixId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Author");

                    b.Navigation("GrandPrix");
                });

            modelBuilder.Entity("Entities.Models.News.Comment", b =>
                {
                    b.HasOne("Entities.Models.News.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.Models.News.Comment", "ReplyToComment")
                        .WithMany()
                        .HasForeignKey("ReplyToCommentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("ReplyToComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Models.Polls.Poll", b =>
                {
                    b.HasOne("Entities.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Entities.Models.Polls.PollOption", b =>
                {
                    b.HasOne("Entities.Models.Polls.Poll", "Poll")
                        .WithMany()
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("Entities.Models.Polls.Vote", b =>
                {
                    b.HasOne("Entities.Models.Polls.PollOption", "PollOption")
                        .WithMany()
                        .HasForeignKey("PollOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PollOption");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Models.RaceTracks.GrandPrix", b =>
                {
                    b.HasOne("Entities.Models.RaceTracks.Circuit", "Circuit")
                        .WithMany()
                        .HasForeignKey("CircuitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.Models.Standings.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Circuit");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Entities.Models.Standings.Constructor", b =>
                {
                    b.HasOne("Entities.Models.Standings.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Entities.Models.Standings.ConstructorCompetition", b =>
                {
                    b.HasOne("Entities.Models.Standings.ConstructorsChampionship", "ConstructorsChampionship")
                        .WithMany()
                        .HasForeignKey("ConstChampId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.Models.Standings.Constructor", "Constructor")
                        .WithMany()
                        .HasForeignKey("ConstructorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Constructor");

                    b.Navigation("ConstructorsChampionship");
                });

            modelBuilder.Entity("Entities.Models.Standings.ConstructorsChampionship", b =>
                {
                    b.HasOne("Entities.Models.Standings.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Entities.Models.Standings.Contract", b =>
                {
                    b.HasOne("Entities.Models.Standings.Constructor", "Constructor")
                        .WithMany()
                        .HasForeignKey("ConstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Standings.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constructor");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Entities.Models.Standings.DriverParticipation", b =>
                {
                    b.HasOne("Entities.Models.Standings.DriversChampionship", "DriversChampionship")
                        .WithMany()
                        .HasForeignKey("DriverChampId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.Models.Standings.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("DriversChampionship");
                });

            modelBuilder.Entity("Entities.Models.Standings.DriversChampionship", b =>
                {
                    b.HasOne("Entities.Models.Standings.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Entities.Models.Standings.Result", b =>
                {
                    b.HasOne("Entities.Models.Standings.ConstructorsChampionship", "ConsChampionship")
                        .WithMany()
                        .HasForeignKey("ConsChampId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.Models.Standings.Constructor", "Constructor")
                        .WithMany()
                        .HasForeignKey("ConstructorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.Models.Standings.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.Models.Standings.DriversChampionship", "DriversChampionship")
                        .WithMany()
                        .HasForeignKey("DriversChampId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.Models.RaceTracks.GrandPrix", "GrandPrix")
                        .WithMany()
                        .HasForeignKey("GrandPrixId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ConsChampionship");

                    b.Navigation("Constructor");

                    b.Navigation("Driver");

                    b.Navigation("DriversChampionship");

                    b.Navigation("GrandPrix");
                });
#pragma warning restore 612, 618
        }
    }
}
