/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConstructorSeasonResultDto } from '../../models/constructor-season-result-dto';

export interface ApiStandingsGetSeasonOverviewDriverChampIdGet$Json$Params {
  driverChampId: string;
}

export function apiStandingsGetSeasonOverviewDriverChampIdGet$Json(http: HttpClient, rootUrl: string, params: ApiStandingsGetSeasonOverviewDriverChampIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ConstructorSeasonResultDto>>> {
  const rb = new RequestBuilder(rootUrl, apiStandingsGetSeasonOverviewDriverChampIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('driverChampId', params.driverChampId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ConstructorSeasonResultDto>>;
    })
  );
}

apiStandingsGetSeasonOverviewDriverChampIdGet$Json.PATH = '/api/Standings/getSeasonOverview/{driverChampId}';
