/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiStandingsRecalculateSessionGrandPrixIdSessionPost$Params {
  grandPrixId: string;
  session: string;
}

export function apiStandingsRecalculateSessionGrandPrixIdSessionPost(http: HttpClient, rootUrl: string, params: ApiStandingsRecalculateSessionGrandPrixIdSessionPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiStandingsRecalculateSessionGrandPrixIdSessionPost.PATH, 'post');
  if (params) {
    rb.path('grandPrixId', params.grandPrixId, {});
    rb.path('session', params.session, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiStandingsRecalculateSessionGrandPrixIdSessionPost.PATH = '/api/Standings/recalculateSession/{grandPrixId}/{session}';
