/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SessionEditDto } from '../../models/session-edit-dto';

export interface ApiStandingsGetSessionForEditGrandPrixIdSessionGet$Plain$Params {
  grandPrixId: string;
  session: string;
}

export function apiStandingsGetSessionForEditGrandPrixIdSessionGet$Plain(http: HttpClient, rootUrl: string, params: ApiStandingsGetSessionForEditGrandPrixIdSessionGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<SessionEditDto>> {
  const rb = new RequestBuilder(rootUrl, apiStandingsGetSessionForEditGrandPrixIdSessionGet$Plain.PATH, 'get');
  if (params) {
    rb.path('grandPrixId', params.grandPrixId, {});
    rb.path('session', params.session, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SessionEditDto>;
    })
  );
}

apiStandingsGetSessionForEditGrandPrixIdSessionGet$Plain.PATH = '/api/Standings/getSessionForEdit/{grandPrixId}/{session}';
