/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DefaultFiltersDto } from '../../models/default-filters-dto';

export interface ApiStandingsGetDefaultFiltersGet$Plain$Params {
}

export function apiStandingsGetDefaultFiltersGet$Plain(http: HttpClient, rootUrl: string, params?: ApiStandingsGetDefaultFiltersGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<DefaultFiltersDto>> {
  const rb = new RequestBuilder(rootUrl, apiStandingsGetDefaultFiltersGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DefaultFiltersDto>;
    })
  );
}

apiStandingsGetDefaultFiltersGet$Plain.PATH = '/api/Standings/getDefaultFilters';
