/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DriverStandingsDto } from '../../models/driver-standings-dto';

export interface ApiStandingsGetByDriversChampionshipIdDriversChampIdGet$Json$Params {
  driversChampId: string;
}

export function apiStandingsGetByDriversChampionshipIdDriversChampIdGet$Json(http: HttpClient, rootUrl: string, params: ApiStandingsGetByDriversChampionshipIdDriversChampIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<DriverStandingsDto>> {
  const rb = new RequestBuilder(rootUrl, apiStandingsGetByDriversChampionshipIdDriversChampIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('driversChampId', params.driversChampId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DriverStandingsDto>;
    })
  );
}

apiStandingsGetByDriversChampionshipIdDriversChampIdGet$Json.PATH = '/api/Standings/getByDriversChampionshipId/{driversChampId}';
