/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SeriesLookupDto } from '../../models/series-lookup-dto';

export interface ApiStandingsGetAllSeriesGet$Json$Params {
}

export function apiStandingsGetAllSeriesGet$Json(http: HttpClient, rootUrl: string, params?: ApiStandingsGetAllSeriesGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SeriesLookupDto>>> {
  const rb = new RequestBuilder(rootUrl, apiStandingsGetAllSeriesGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SeriesLookupDto>>;
    })
  );
}

apiStandingsGetAllSeriesGet$Json.PATH = '/api/Standings/getAllSeries';
