/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SeasonOverviewDto } from '../../models/season-overview-dto';

export interface ApiStandingsGetSeasonOverviewDriverChampIdGet$Plain$Params {
  driverChampId: string;
}

export function apiStandingsGetSeasonOverviewDriverChampIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiStandingsGetSeasonOverviewDriverChampIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SeasonOverviewDto>>> {
  const rb = new RequestBuilder(rootUrl, apiStandingsGetSeasonOverviewDriverChampIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('driverChampId', params.driverChampId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SeasonOverviewDto>>;
    })
  );
}

apiStandingsGetSeasonOverviewDriverChampIdGet$Plain.PATH = '/api/Standings/getSeasonOverview/{driverChampId}';
