/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DriverLookUpDto } from '../../models/driver-look-up-dto';

export interface ApiStandingsGetDriversByDriversChampionshipDriverChampIdGet$Json$Params {
  driverChampId: string;
}

export function apiStandingsGetDriversByDriversChampionshipDriverChampIdGet$Json(http: HttpClient, rootUrl: string, params: ApiStandingsGetDriversByDriversChampionshipDriverChampIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DriverLookUpDto>>> {
  const rb = new RequestBuilder(rootUrl, apiStandingsGetDriversByDriversChampionshipDriverChampIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('driverChampId', params.driverChampId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DriverLookUpDto>>;
    })
  );
}

apiStandingsGetDriversByDriversChampionshipDriverChampIdGet$Json.PATH = '/api/Standings/getDriversByDriversChampionship/{driverChampId}';
