/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConstructorStandingsDto } from '../../models/constructor-standings-dto';

export interface ApiStandingsGetByConstructorChampionshipIdConstructsChampIdGet$Plain$Params {
  constructsChampId: string;
}

export function apiStandingsGetByConstructorChampionshipIdConstructsChampIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiStandingsGetByConstructorChampionshipIdConstructsChampIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ConstructorStandingsDto>> {
  const rb = new RequestBuilder(rootUrl, apiStandingsGetByConstructorChampionshipIdConstructsChampIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('constructsChampId', params.constructsChampId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ConstructorStandingsDto>;
    })
  );
}

apiStandingsGetByConstructorChampionshipIdConstructsChampIdGet$Plain.PATH = '/api/Standings/getByConstructorChampionshipId/{constructsChampId}';
