/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ParticipationListDto } from '../../models/participation-list-dto';

export interface ApiStandingsGetParticipationsDriversChampIdConstructorsChampIdGet$Json$Params {
  driversChampId: string;
  constructorsChampId: string;
}

export function apiStandingsGetParticipationsDriversChampIdConstructorsChampIdGet$Json(http: HttpClient, rootUrl: string, params: ApiStandingsGetParticipationsDriversChampIdConstructorsChampIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ParticipationListDto>> {
  const rb = new RequestBuilder(rootUrl, apiStandingsGetParticipationsDriversChampIdConstructorsChampIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('driversChampId', params.driversChampId, {});
    rb.path('constructorsChampId', params.constructorsChampId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ParticipationListDto>;
    })
  );
}

apiStandingsGetParticipationsDriversChampIdConstructorsChampIdGet$Json.PATH = '/api/Standings/getParticipations/{driversChampId}/{constructorsChampId}';
