/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ParticipationListDto } from '../../models/participation-list-dto';

export interface ApiStandingsGetParticipationsDriversChampIdConstructorsChampIdGet$Plain$Params {
  driversChampId: string;
  constructorsChampId: string;
}

export function apiStandingsGetParticipationsDriversChampIdConstructorsChampIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiStandingsGetParticipationsDriversChampIdConstructorsChampIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ParticipationListDto>> {
  const rb = new RequestBuilder(rootUrl, apiStandingsGetParticipationsDriversChampIdConstructorsChampIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('driversChampId', params.driversChampId, {});
    rb.path('constructorsChampId', params.constructorsChampId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ParticipationListDto>;
    })
  );
}

apiStandingsGetParticipationsDriversChampIdConstructorsChampIdGet$Plain.PATH = '/api/Standings/getParticipations/{driversChampId}/{constructorsChampId}';
