/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiStandingsUpdateChampionshipStatusDriversChampIdConstructorsChampIdStatusPost$Params {
  driversChampId: string;
  constructorsChampId: string;
  status: string;
}

export function apiStandingsUpdateChampionshipStatusDriversChampIdConstructorsChampIdStatusPost(http: HttpClient, rootUrl: string, params: ApiStandingsUpdateChampionshipStatusDriversChampIdConstructorsChampIdStatusPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiStandingsUpdateChampionshipStatusDriversChampIdConstructorsChampIdStatusPost.PATH, 'post');
  if (params) {
    rb.path('driversChampId', params.driversChampId, {});
    rb.path('constructorsChampId', params.constructorsChampId, {});
    rb.path('status', params.status, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiStandingsUpdateChampionshipStatusDriversChampIdConstructorsChampIdStatusPost.PATH = '/api/Standings/updateChampionshipStatus/{driversChampId}/{constructorsChampId}/{status}';
