/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GrandPrixChampionshipContextDto } from '../../models/grand-prix-championship-context-dto';

export interface ApiStandingsGetGrandPrixContextGrandPrixIdGet$Json$Params {
  grandPrixId: string;
}

export function apiStandingsGetGrandPrixContextGrandPrixIdGet$Json(http: HttpClient, rootUrl: string, params: ApiStandingsGetGrandPrixContextGrandPrixIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<GrandPrixChampionshipContextDto>> {
  const rb = new RequestBuilder(rootUrl, apiStandingsGetGrandPrixContextGrandPrixIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('grandPrixId', params.grandPrixId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GrandPrixChampionshipContextDto>;
    })
  );
}

apiStandingsGetGrandPrixContextGrandPrixIdGet$Json.PATH = '/api/Standings/getGrandPrixContext/{grandPrixId}';
