/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ChampionshipRowDto } from '../../models/championship-row-dto';

export interface ApiStandingsGetAllChampionshipsBySeriesSeriesIdGet$Plain$Params {
  seriesId: string;
}

export function apiStandingsGetAllChampionshipsBySeriesSeriesIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiStandingsGetAllChampionshipsBySeriesSeriesIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ChampionshipRowDto>>> {
  const rb = new RequestBuilder(rootUrl, apiStandingsGetAllChampionshipsBySeriesSeriesIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('seriesId', params.seriesId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ChampionshipRowDto>>;
    })
  );
}

apiStandingsGetAllChampionshipsBySeriesSeriesIdGet$Plain.PATH = '/api/Standings/getAllChampionshipsBySeries/{seriesId}';
