/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DefaultFiltersDto } from '../../models/default-filters-dto';

export interface ApiStandingsGetDefaultFiltersGet$Json$Params {
}

export function apiStandingsGetDefaultFiltersGet$Json(http: HttpClient, rootUrl: string, params?: ApiStandingsGetDefaultFiltersGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<DefaultFiltersDto>> {
  const rb = new RequestBuilder(rootUrl, apiStandingsGetDefaultFiltersGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DefaultFiltersDto>;
    })
  );
}

apiStandingsGetDefaultFiltersGet$Json.PATH = '/api/Standings/getDefaultFilters';
