/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { YearLookupDto } from '../../models/year-lookup-dto';

export interface ApiStandingsGetSeasonsBySeriesSeriesIdGet$Json$Params {
  seriesId: string;
}

export function apiStandingsGetSeasonsBySeriesSeriesIdGet$Json(http: HttpClient, rootUrl: string, params: ApiStandingsGetSeasonsBySeriesSeriesIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<YearLookupDto>>> {
  const rb = new RequestBuilder(rootUrl, apiStandingsGetSeasonsBySeriesSeriesIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('seriesId', params.seriesId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<YearLookupDto>>;
    })
  );
}

apiStandingsGetSeasonsBySeriesSeriesIdGet$Json.PATH = '/api/Standings/getSeasonsBySeries/{seriesId}';
