/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiChampionshipRemoveConstructorCompetitionConstructorIdConstructorsChampIdDelete$Params {
  constructorId: string;
  constructorsChampId: string;
}

export function apiChampionshipRemoveConstructorCompetitionConstructorIdConstructorsChampIdDelete(http: HttpClient, rootUrl: string, params: ApiChampionshipRemoveConstructorCompetitionConstructorIdConstructorsChampIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiChampionshipRemoveConstructorCompetitionConstructorIdConstructorsChampIdDelete.PATH, 'delete');
  if (params) {
    rb.path('constructorId', params.constructorId, {});
    rb.path('constructorsChampId', params.constructorsChampId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiChampionshipRemoveConstructorCompetitionConstructorIdConstructorsChampIdDelete.PATH = '/api/Championship/removeConstructorCompetition/{constructorId}/{constructorsChampId}';
