/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ChampionshipRowDto } from '../../models/championship-row-dto';

export interface ApiChampionshipGetAllChampionshipsBySeriesSeriesIdGet$Json$Params {
  seriesId: string;
}

export function apiChampionshipGetAllChampionshipsBySeriesSeriesIdGet$Json(http: HttpClient, rootUrl: string, params: ApiChampionshipGetAllChampionshipsBySeriesSeriesIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ChampionshipRowDto>>> {
  const rb = new RequestBuilder(rootUrl, apiChampionshipGetAllChampionshipsBySeriesSeriesIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('seriesId', params.seriesId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ChampionshipRowDto>>;
    })
  );
}

apiChampionshipGetAllChampionshipsBySeriesSeriesIdGet$Json.PATH = '/api/Championship/getAllChampionshipsBySeries/{seriesId}';
