/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiChampionshipRemoveDriverParticipationDriverIdDriversChampIdDelete$Params {
  driverId: string;
  driversChampId: string;
}

export function apiChampionshipRemoveDriverParticipationDriverIdDriversChampIdDelete(http: HttpClient, rootUrl: string, params: ApiChampionshipRemoveDriverParticipationDriverIdDriversChampIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiChampionshipRemoveDriverParticipationDriverIdDriversChampIdDelete.PATH, 'delete');
  if (params) {
    rb.path('driverId', params.driverId, {});
    rb.path('driversChampId', params.driversChampId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiChampionshipRemoveDriverParticipationDriverIdDriversChampIdDelete.PATH = '/api/Championship/removeDriverParticipation/{driverId}/{driversChampId}';
