/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConstructorLookUpDto } from '../../models/constructor-look-up-dto';

export interface ApiChampionshipGetConstructorsByConstructorsChampionshipConstChampIdGet$Json$Params {
  constChampId: string;
}

export function apiChampionshipGetConstructorsByConstructorsChampionshipConstChampIdGet$Json(http: HttpClient, rootUrl: string, params: ApiChampionshipGetConstructorsByConstructorsChampionshipConstChampIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ConstructorLookUpDto>>> {
  const rb = new RequestBuilder(rootUrl, apiChampionshipGetConstructorsByConstructorsChampionshipConstChampIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('constChampId', params.constChampId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ConstructorLookUpDto>>;
    })
  );
}

apiChampionshipGetConstructorsByConstructorsChampionshipConstChampIdGet$Json.PATH = '/api/Championship/getConstructorsByConstructorsChampionship/{constChampId}';
